config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: :show do
    resources :items, only: %i(show edit update destroy), controller: 'users/items'
    member do
      get 'private_items'
      get 'comments'
    end
  end
  resources :items, only: %i(index new create) do
    resources :comments, only: %i(create destroy)
    resources :stocks, only: %i(create destroy)
  end
  resources :stocks, only: :index
  resources :tags, except: [:new, :edit]
  root 'home#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :item
  validates :body, presence: true
end

app/models/follow_tag.rb
class FollowTag < ActiveRecord::Base
  belongs_to :user
  belongs_to :tag
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_many :stocks
  has_many :tags, through: :item_tags
  has_many :item_tags
  accepts_nested_attributes_for :tags
  validates :title, :body, presence: true

  def tags_attributes=(params)
    if tags = params['0']['name']
      tags.gsub('　', ' ').split(' ').each do |tag_name|
        tag = Tag.find_or_create_by!(name: tag_name)
        self.item_tags.find_or_initialize_by(tag: tag)
      end
    end
  end
end

app/models/item_tag.rb
class ItemTag < ActiveRecord::Base
  belongs_to :item
  belongs_to :tag
end

app/models/stock.rb
class Stock < ActiveRecord::Base
  belongs_to :user
  belongs_to :item
  validates :user_id, uniqueness: { scope: :item_id }
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :items, through: :item_tags
  has_many :item_tags
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :items
  has_many :comments
  has_many :stocks
  has_many :tags, through: :follow_tags
  has_many :follow_tags
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, presence: true

  def stock?(item)
    stocks.find_by(item_id: item)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  
  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation) }
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_item

  def create
    @comment = @item.comments.build(comment_params)
    @comment.user = current_user
    @comment.save
    redirect_to user_item_path(current_user, @item)
  end

  private

    def set_item
      @item = Item.find(params[:item_id])
    end

    def comment_params
      params.require(:comment).permit(:body)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @items = Item.all
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def new
    @item = current_user.items.build
    @item.tags.build
  end

  def create
    @item = current_user.items.build(item_params)
    if @item.save
      redirect_to user_item_path(current_user, @item)
    else
      render 'new'
    end
  end

  private

    def item_params
      params.require(:item).permit(:title, :body, tags_attributes: [:name])
    end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_item, except: :index

  def index
    @stocks = current_user.stocks.all
  end

  def create
    @stock = @item.stocks.build
    @stock.user = current_user
    @stock.save
    respond_to do |format|
      format.html { redirect_to user_item_path(current_user, @item) }
      format.js
    end
  end

  def destroy
    Stock.find(params[:id]).destroy
    respond_to do |format|
      format.html { redirect_to user_item_path(current_user, @item) }
      format.js
    end
  end

  private

    def set_item
      @item = Item.find(params[:item_id])
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
  end
  
end

app/controllers/users/items_controller.rb
class Users::ItemsController < ApplicationController
  before_action :set_item, except: :show

  def show
    @item = Item.find(params[:id])
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to user_item_path(current_user, @item)
    else
      render 'edit'
    end
  end

  def destroy
    @item.destroy
    redirect_to root_url
  end

  private

    def set_item
      @item = current_user.items.find(params[:id])
    end

    def item_params
      params.require(:item).permit(:title, :body, tags_attributes: [:name])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def private_items
    @items = current_user.items.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users/items_helper.rb
module Users::ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/index.html.haml
.container
  .row
    .col-sm-8
      %h2 プログラミング知識を共有しよう。
      = link_to 'ノウハウ・Tipsを投稿する', new_item_path, class: 'btn btn-success'
      %ul.nav.nav-tabs
        %li
          = link_to 'フィード', root_path
        %li.active
          = link_to 'すべての投稿', items_path
        %li.pull-right
          = link_to '自分の投稿', private_items_user_path(current_user)
        %li.pull-right
          = link_to 'ストック', stocks_path
      - @items.each do |item|
        .user_name
          = link_to item.user.username, user_path(item.user)
        .title
          = link_to item.title, user_item_path(item.user, item)
    .col-sm-3.col-sm-offset-1
      %p ユーザ名

app/views/items/new.html.haml
%h1 new

= form_for @item do |f|
  = f.label :title
  - if @item.errors.any?
    = @item.errors.messages[:title][0]
  = f.text_field :title
  %br
  = f.fields_for :tags do |tag|
    = tag.label :name
    = tag.text_field :name
  %br
  = f.label :body
  - if @item.errors.any?
    = @item.errors.messages[:body][0]
  = f.text_area :body
  %br
  = f.submit

app/views/stocks/create.js.erb
$('#follow_form').html("<%= j render 'users/items/unstock' %>")

app/views/stocks/destroy.js.erb
$('#follow_form').html("<%= j render 'users/items/stock' %>")

app/views/stocks/index.html.haml
.container
  .row
    .col-sm-8
      %h2 プログラミング知識を共有しよう。
      = link_to 'ノウハウ・Tipsを投稿する', new_item_path, class: 'btn btn-success'
      %ul.nav.nav-tabs
        %li
          = link_to 'フィード', root_path
        %li
          = link_to 'すべての投稿', items_path
        %li.pull-right
          = link_to '自分の投稿', private_items_user_path(current_user)
        %li.pull-right.active
          = link_to 'ストック', stocks_path
      - @stocks.each do |stock|
        .user_name
          = link_to stock.user.username, user_path(stock.user)
        .title
          = link_to stock.item.title, user_item_path(stock.user, stock.item)
    .col-sm-3.col-sm-offset-1
      %p ユーザ名

app/views/tags/index.html.haml
%ul
  - @tags.each do |tag|
    %li= link_to tag.name, tag_path(tag)

app/views/tags/show.html.haml
%h1= @tag.name

app/views/users/items/_stock.html.haml
= form_for([@item, @item.stocks.build], remote: true) do |f|
  = f.submit 'ストック'

app/views/users/items/_unstock.html.haml
= form_for([@item, @item.stocks.find_by(user_id: current_user.id)], remote: true, html: {method: :delete}) do |f|
  = f.submit '解除'

app/views/users/items/edit.html.haml
%h1 edit

= form_for [current_user, @item] do |f|
  = f.label :title
  - if @item.errors.any?
    = @item.errors.messages[:title][0]
  = f.text_field :title
  %br
  = f.fields_for :tags do |tag|
    = tag.label :name
    = tag.text_field :name
  %br
  = f.label :body
  - if @item.errors.any?
    = @item.errors.messages[:body][0]
  = f.text_area :body
  %br
  = f.submit

app/views/users/items/show.html.haml
%h2= 'タイトル'
= @item.title
%br
%h2= 'タグ'
- @item.tags.each do |tag|
  = tag.name
%br
%h2= '本文'
= @item.body
%br
= link_to '編集する', edit_user_item_path(@item.user, @item)
= link_to '削除する', user_item_path(@item.user, @item), method: :delete, data: { confirm: 'Are you sure?' }

%h2= 'コメント'
.comment
  - @item.comments.each do |comment|
    .comment_user
      = comment.user.username
    .comment_body
      = comment.body
= form_for [@item, @item.comments.build] do |f|
  = f.text_area :body
  %br
  = f.submit

%br

#follow_form
  - if current_user.stock?(@item)
    = render 'unstock'
  - else
    = render 'stock'

app/views/users/private_items.html.haml
.container
  .row
    .col-sm-8
      %h2 プログラミング知識を共有しよう。
      = link_to 'ノウハウ・Tipsを投稿する', new_item_path, class: 'btn btn-success'
      %ul.nav.nav-tabs
        %li
          = link_to 'フィード', root_path
        %li
          = link_to 'すべての投稿', items_path
        %li.pull-right.active
          = link_to '自分の投稿', private_items_user_path(current_user)
        %li.pull-right
          = link_to 'ストック', stocks_path
      - @items.each do |item|
        .user_name
          = link_to item.user.username, user_path(item.user)
        .title
          = link_to item.title, user_item_path(item.user, item)
    .col-sm-3.col-sm-offset-1
      %p ユーザ名

app/views/users/show.html.haml
= current_user.username